"""Portable, dependency-free HTML trace dashboard."""
import json
from pathlib import Path
from .metrics import aggregate


def render_dashboard(events, output_path):
    events = list(events)
    report = aggregate(events)
    data = json.dumps({"events": events, "report": report}, ensure_ascii=True).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    html = _HTML.replace("__TRACE_DATA__", data)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html, encoding="utf-8")
    return report


_HTML = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent Harness · Experiment report</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0d1320;color:#edf2fa}*{box-sizing:border-box}body{margin:0}main{max-width:1320px;margin:auto;padding:44px 28px}header{display:flex;justify-content:space-between;align-items:center;gap:24px}.eyebrow{color:#74dbc7;font-size:12px;letter-spacing:2px;text-transform:uppercase}h1{font-size:38px;letter-spacing:-1.5px;margin:12px 0}p,.muted{color:#9eafc8;line-height:1.65}.badge{border:1px solid #42546d;border-radius:30px;padding:8px 14px;font-size:12px}section{margin-top:32px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.card,.panel{border:1px solid #28364e;border-radius:14px;background:#131e30;padding:22px}.label{color:#9eafc8;font-size:13px}.value{font-size:30px;margin-top:12px;font-variant-numeric:tabular-nums}h2{font-size:19px;font-weight:550;margin:0 0 18px}select{background:#17243b;color:#fff;border:1px solid #42546d;padding:10px;border-radius:8px;margin-left:8px}.toolbar{display:flex;gap:18px;flex-wrap:wrap;align-items:center;margin-bottom:24px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:13px 10px;border-bottom:1px solid #28364e;white-space:nowrap}th{color:#9eafc8;font-weight:500}.scroll{overflow:auto}.trace{display:grid;grid-template-columns:220px 1fr;gap:12px;align-items:center;margin:12px 0;font-size:12px}.track{height:24px;background:#0d1320;border-radius:4px;position:relative}.bar{height:100%;position:absolute;min-width:3px;border-radius:4px;background:#67d5c0}.trace-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.note{font-size:12px}.empty{padding:25px;color:#9eafc8}footer{margin-top:30px;color:#9eafc8;font-size:12px}@media(max-width:760px){main{padding:24px 16px}.cards{grid-template-columns:repeat(2,1fr)}header{display:block}h1{font-size:30px}.trace{grid-template-columns:120px 1fr}.badge{display:inline-block}}</style>
<main><header><div><div class="eyebrow">Agent Harness Lab / Measurements</div><h1>Inside the agent workload.</h1><p>Latency, usage, and execution traces from recorded experiments.</p></div><span class="badge" id="mode"></span></header>
<section class="cards" id="cards"></section>
<section class="panel"><h2>Provider & model comparison</h2><div class="scroll"><table><thead><tr><th>Provider / Model</th><th>Requests</th><th>p95 latency</th><th>p50 TTFT</th><th>Output tok/s</th><th>Peak concurrency</th></tr></thead><tbody id="comparison"></tbody></table></div></section>
<section class="panel"><h2>Architecture outcomes</h2><div class="scroll"><table><thead><tr><th>Architecture</th><th>Trials</th><th>Synthetic</th><th>Success</th><th>p95 wall time</th></tr></thead><tbody id="architectures"></tbody></table></div></section>
<section class="panel"><h2>Execution timeline</h2><div class="toolbar"><label>Run<select id="run"></select></label><label>Task<select id="task"><option value="">All tasks</option></select></label><label>Event<select id="event"><option value="">All events</option><option>request</option><option>tool</option><option>trial</option></select></label><span class="muted note" id="count"></span></div><div id="timeline"></div><p class="note">Bars share a relative time axis within the selected run. Hover for duration. Filters affect only the timeline; summary cards cover the entire trace.</p></section>
<section class="panel"><h2>How to read these measurements</h2><div id="notes"></div><p class="note">Token counts may be estimated when labeled by the provider. Missing usage is shown as —. Chunk intervals are never presented as token intervals. Traces can contain sensitive payloads; review before sharing.</p></section><footer>Self-contained report · No network requests · Generated from recorded trace events</footer></main>
<script id="trace-data" type="application/json">__TRACE_DATA__</script><script>
const data=JSON.parse(document.getElementById('trace-data').textContent), r=data.report, q=r.requests;
const fmt=(x,s='')=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:2})+s;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
document.getElementById('mode').textContent=r.trials.synthetic ? `${r.trials.synthetic} synthetic trial(s) · ${r.trials.count-r.trials.synthetic} other trial(s)`:'Observed trace';
for(const [label,value] of [['Request attempts',q.count],['p95 request latency',fmt(q.latency_ms.p95,' ms')],['Trial success rate',fmt(r.trials.success_rate==null?null:r.trials.success_rate*100,'%')],['Output throughput',fmt(q.output_tokens_per_second,' tok/s')],['p50 token ITL',fmt(q.token_itl_ms.p50,' ms')],['p50 derived chunk TPOT',fmt(q.derived_chunk_tpot_ms.p50,' ms')],['Total tokens',fmt(r.efficiency.total_tokens)],['Configured-rate cost',fmt(r.efficiency.configured_rate_total_cost)]]){let n=node('div',undefined,'card');n.append(node('div',label,'label'),node('div',String(value),'value'));document.getElementById('cards').append(n)}
for(const g of r.by_provider_model){const row=node('tr');for(const value of [g.provider+' / '+g.model,g.count,fmt(g.latency_ms.p95,' ms'),fmt(g.ttft_ms.p50,' ms'),fmt(g.output_tokens_per_second),g.peak_concurrent_requests])row.append(node('td',String(value)));document.getElementById('comparison').append(row)}
for(const g of r.by_architecture){const row=node('tr');for(const value of [g.architecture,g.trials,g.synthetic_trials,fmt(g.success_rate==null?null:g.success_rate*100,'%'),fmt(g.latency_ms.p95,' ms')])row.append(node('td',String(value)));document.getElementById('architectures').append(row)}
for(const note of [...r.notes,`Estimated token requests: ${q.estimated_token_requests}. Actual token interval samples: ${q.token_itl_ms.count}. Content chunk interval samples: ${q.chunk_interval_ms.count}.`])document.getElementById('notes').append(node('p',note,'note'));
const task=document.getElementById('task'),event=document.getElementById('event'),run=document.getElementById('run');for(const id of [...new Set(data.events.map(e=>String(e.run_id??'')))].sort()){let o=node('option',id||'Unspecified');o.value=id;run.append(o)}for(const id of [...new Set(data.events.map(e=>String(e.task_id??'')))].sort()){if(id){let o=node('option',id);o.value=id;task.append(o)}}
function draw(){const target=document.getElementById('timeline');target.replaceChildren();const es=data.events.filter(e=>String(e.run_id??'')===run.value&&(!task.value||String(e.task_id)===task.value)&&(!event.value||e.event===event.value)&&Number.isFinite(e.start_ns)&&Number.isFinite(e.end_ns)&&e.end_ns>=e.start_ns).sort((a,b)=>a.start_ns-b.start_ns);document.getElementById('count').textContent=es.length+' timed events';if(!es.length){target.append(node('div','No timed events for this selection.','empty'));return}const start=es[0].start_ns,end=es.reduce((v,e)=>Math.max(v,e.end_ns),es[0].end_ns),span=Math.max(1,end-start);for(const e of es){let row=node('div',undefined,'trace'),label=node('div',`${e.event} · ${e.task_id??''} · ${e.agent_id??''}`,'trace-label'),track=node('div',undefined,'track'),bar=node('div',undefined,'bar');bar.style.left=((e.start_ns-start)/span*100)+'%';bar.style.width=((e.end_ns-e.start_ns)/span*100)+'%';bar.style.background=e.event==='trial'?'#7895ed':e.event==='tool'?'#d6a66f':'#67d5c0';bar.title=fmt((e.end_ns-e.start_ns)/1e6,' ms')+' · '+(e.status??'');track.append(bar);row.append(label,track);target.append(row)}}task.onchange=event.onchange=run.onchange=draw;draw();
</script></html>'''
